spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost/date_girl1?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql

girl:
  file:
    path:
      faceImage:
        absolutePath: /home/test/girl/image/face/
        relativePath: /image/girl/image/face/
      backImage:
        absolutePath: /home/test/girl/image/back/
        relativePath: /image/girl/image/back/
      sideImage:
        absolutePath: /home/test/girl/image/side/
        relativePath: /image/girl/image/side/
      blurImage:
        absolutePath: /home/test/girl/image/blur/
        relativePath: /image/girl/image/blur/
      frontImage:
        absolutePath: /home/test/girl/image/front/
        relativePath: /image/girl/image/front/

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days